# Generated by Django 4.2.6 on 2024-03-17 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_visitcounter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitcounter",
            name="counter",
        ),
        migrations.AddField(
            model_name="visitcounter",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
